name: CI - Configure, Build, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      matrix:
        systems: [ self-ubuntu-24.04 , karolina ]
    runs-on: ${{ matrix.systems }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure the Build System
        run: |
          cmake --preset default

      - name: Build the Project
        run: |
          cmake --build --preset default

      - name: Run Tests
        run: |
          ctest --preset default